# permissions for end users to view jwks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jwk-viewer-role
rules:
- apiGroups:
  - juc.conhumi.net
  resources:
  - jwks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - juc.conhumi.net
  resources:
  - jwks/status
  verbs:
  - get
