# permissions for end users to edit jwks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jwk-editor-role
rules:
- apiGroups:
  - juc.conhumi.net
  resources:
  - jwks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - juc.conhumi.net
  resources:
  - jwks/status
  verbs:
  - get
